// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    welcomeSidebar: [
    {
        "type": "category",
        "label": "Quick Start",
        "items": [
            {
                "type": "autogenerated",
                "dirName": "01_quick-start"
            }
        ],
        "collapsed": false
    },
    {
        "type": "category",
        "label": "Core Concepts",
        "items": [
            {
                "type": "autogenerated",
                "dirName": "02_core-concepts"
            }
        ],
        "collapsed": false
    },
    {
        "type": "category",
        "label": "Smart Contracts",
        "items": [
            {
                "type": "autogenerated",
                "dirName": "03_smart-contracts"
            }
        ],
        "collapsed": false
    },
    {
        "type": "category",
        "label": "Web Applications",
        "items": [
            {
                "type": "autogenerated",
                "dirName": "04_web-applications"
            }
        ],
        "collapsed": false
    },
    {
        "type": "category",
        "label": "EOS EVM",
        "items": [
            {
                "type": "autogenerated",
                "dirName": "05_eos-evm"
            }
        ],
        "collapsed": false
    },
    {
        "type": "category",
        "label": "Guides",
        "items": [
            {
                "type": "autogenerated",
                "dirName": "06_guides"
            }
        ],
        "collapsed": false
    },
    {
        "type": "category",
        "label": "Node Operation",
        "items": [
            {
                "type": "autogenerated",
                "dirName": "07_node-operation"
            }
        ],
        "collapsed": false
    },
    {
        "type": "category",
        "label": "Advanced Topics",
        "items": [
            {
                "type": "autogenerated",
                "dirName": "60_advanced-topics"
            }
        ],
        "collapsed": false
    },
    {
        "type": "category",
        "label": "Miscellaneous",
        "items": [
            {
                "type": "autogenerated",
                "dirName": "999_miscellaneous"
            }
        ],
        "collapsed": false
    }
]
};
    
module.exports = sidebars;