// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // welcomeSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.'
  //   },
  // ],

    // But you can create a sidebar manually
    welcomeSidebar: [
      {
        type: 'category',
        label: 'Welcome',
        items: [
          {
            type: 'doc',
            id: 'getting-started/introduction',
          }
        ]
      }
    ]
};

module.exports = sidebars;

/*
{
    'Getting Started': [
      '01_getting-started/10_introduction',
      '01_getting-started/20_web-ide',
      '01_getting-started/30_dune-guide'
    ],
    'Core Concepts': [
      '02_core-concepts/10_blockchain-101',
      '02_core-concepts/20_accounts',
      '02_core-concepts/30_resources'
    ],
    'Build, Test & Deploy': [
      '03_build-test-deploy/10_project-structure',
      '03_build-test-deploy/20_smart-contract-basics',
      '03_build-test-deploy/30_actions',
      '03_build-test-deploy/40_assets',
      '03_build-test-deploy/50_reading-data'
    ],
    'Web Applications': [ '04_web-applications/10_getting-started' ]
  }
 */


/*
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

// @ts-check

// @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
};

module.exports = sidebars;

 */
