name: Check broken links

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch of the docs repo to build'
        required: true
        default: 'staging'

jobs:
  build-and-prepare-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm install

      - name: Prepare Docs
        run: node scripts/prepare-docs --docs-branch=${{ github.event.inputs.branch }}

      - name: Run links check
        run: node scripts/check-links
